let BookArray = [
  {
    name: "The King of Drugs",
    author: "NORA BARRETT",
    noOfPages: 40,
    categories: "health",
    ratings: 4.5,
    price: 30,
    lendingPrice: 5,
    published: 2020,
  },
  {
    name: "Creative Business Startup",
    author: "JEN BRAZEL",
    noOfPages: 40,
    categories: "business",
    ratings: 4.5,
    price: 30,
    lendingPrice: 5,
    published: 2022,
  },
  {
    name: "Made to Impress",
    author: "ANDREW CRIS",
    noOfPages: 56,
    categories: "art",
    ratings: 4.65,
    price: 34,
    lendingPrice: 8,
    published: 2021,
  },
  {
    name: "Lost Stars",
    author: "RITA SKEETER",
    noOfPages: 29,
    categories: "geography",
    ratings: 5.0,
    price: 50,
    lendingPrice: 15,
    published: 2022,
  },
  {
    name: "Make Everyday Valentines Days",
    author: "MEGAN CREWS",
    noOfPages: 56,
    categories: "romance",
    ratings: 4.2,
    price: 28,
    lendingPrice: 4,
    published: 2022,
  },
  {
    name: "Peace and War",
    author: "KEN ADAMS",
    noOfPages: 47,
    categories: "history",
    ratings: 4.9,
    price: 42,
    lendingPrice: 7,
    published: 2019,
  },
  {
    name: "Planting the Seed of Hope",
    author: "REAGAN BARKER",
    noOfPages: 33,
    categories: "investment",
    ratings: 4.5,
    price: 30,
    lendingPrice: 5,
    published: 2021,
  },
  {
    name: "The Way of The Nameless",
    author: "GRAHAM DOUGLASS",
    noOfPages: 47,
    categories: "motivation",
    ratings: 3.7,
    price: 30,
    lendingPrice: 9,
    published: 2019,
  },
  {
    name: "Away",
    author: "SYLVIA WALKER",
    noOfPages: 41,
    categories: "art",
    ratings: 4.0,
    price: 42,
    lendingPrice: 6,
    published: 2020,
  },
  {
    name: "The Dawn of Light",
    author: "FELICIA LAGERFELT",
    noOfPages: 40,
    categories: "art",
    ratings: 4.9,
    price: 40,
    lendingPrice: 10,
    published: 2019,
  },
];
